"""IComment class Migration

Revision ID: 513cd4730541
Revises: 9ab229914c4e
Create Date: 2021-11-07 15:52:07.918610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513cd4730541'
down_revision = '9ab229914c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
