"""pitch-id column Migration

Revision ID: 612c5e36df9c
Revises: 513cd4730541
Create Date: 2021-11-07 15:54:41.696490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612c5e36df9c'
down_revision = '513cd4730541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'pitch', ['pitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'pitch_id')
    # ### end Alembic commands ###
