"""description Migration

Revision ID: 8d187c85b8e9
Revises: 612c5e36df9c
Create Date: 2021-11-08 14:38:18.488865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d187c85b8e9'
down_revision = '612c5e36df9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'description')
    # ### end Alembic commands ###
